### ISSUE TITLE
bug: gocode gets commands but no autocomplete popup in brackets.

### ISSUE THREAD

**Issue by tschundeee** [David5i6/Brackets-Go-IDE#8]
Hi first let me thank you for creating such a nice plugin for brackets :)

I usually use sublimetext with https://github.com/DisposaBoy/GoSublime for golang but this brackets plugin seems very interesting. 

Unfortunately I can't get it to run properly under osx mavericks using go 1.4.1. I started brackets via terminal (/Applications/Brackets.app/Contents/MacOS/Brackets) and my $GOPATH is ~/go.

gocode is installed via go get -u github.com/nsf/gocode

I started gocode in debug mode (gocode -s -debug) and see that it gets the content from brackets and shows the right suggestions on the command line. Unfortunately there is no code-completion popping up in brackets.

Am I missing something?

Thx and regards
Bijan

**Comment by tschundeee** [comment]
PS: The icons and color theme looks extremely nice. What are you using in the screenshot? :+1:

**Comment by David5i6** [comment]
There was a little change in brackets 1.0, that makes the plugin miss external events.
For some estrange reason in my updated brackets it runs perfect.
I've made some little changes and tested in 3 different 'clean' brackets 1.0 installations, so I expect autocomplete should work on 0.0.10 version.

PS: the theme is 'Delkos Dark Theme' and icons are from 'brackets icons'  plugin
